<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>JSP Page</title>
    	<!-- Site favicon
	<link rel="apple-touch-icon" sizes="180x180" href="vendors/images/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="vendors/images/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="vendors/images/favicon-16x16.png"> -->

	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
	<!-- CSS -->
	<link rel="stylesheet" type="text/css" href="vendors/styles/core.css">
	<link rel="stylesheet" type="text/css" href="vendors/styles/icon-font.min.css">
	<link rel="stylesheet" type="text/css" href="vendors/styles/style.css">

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-119386393-1"></script>
 
</head>
<body>
    
    
    	
   <%@include file="header.jsp" %>
	<div class="mobile-menu-overlay"></div>

	<div class="main-container">
		<div class="pd-ltr-20 xs-pd-20-10">
			
				
				<div class="row clearfix">
                                    
					<div class="col-md-4 col-sm-12 mb-30">
                                            <a href="registerTeacher.jsp" > 
						<div class="card text-white bg-primary card-box">
							<div class="card-header">Register Teacher</div>
							<div class="card-body">
								<h5 class="card-title text-white"></h5>
		<p class="card-text">before the course is distributed teachers of the department must be added to the system</p>
							</div>
						</div>
                                                </a>
					</div>
                                        
					<div class="col-md-4 col-sm-12 mb-30">
                                              <a href="registerCourse.jsp" > 
						<div class="card text-white bg-secondary card-box">
							<div class="card-header">Register Course</div>
							<div class="card-body">
								<h5 class="card-title text-white">  </h5>
								<p class="card-text">then course of one semester must be recorded in the database</p>
							</div>
                                              
						</div>
                                                  </a>
					</div>
					<div class="col-md-4 col-sm-12 mb-30">
                                            <a href="registerStudent.jsp" > 
						<div class="card text-white bg-success card-box">
							<div class="card-header">Register Student</div>
							<div class="card-body">
								<h5 class="card-title text-white"> </h5>
								<p class="card-text">after we are registering teachers and courses there should be students who inroll in the course.</p>
							</div>
						</div>
                                            </a>
					</div>
					<div class="col-md-4 col-sm-12 mb-30">
                                            <a href="<%= request.getContextPath() %>/CourseAssignment" > 
						<div class="card text-black bg-warning card-box">
							<div class="card-header">Assign Course</div>
							<div class="card-body">
								<h5 class="card-title"> </h5>
								<p class="card-text">now the registered teachers should assigned some courses based on the capabilities.</p>
							</div>
						</div>
                                            </a>
					</div>
					<div class="col-md-4 col-sm-12 mb-30">
                                              <a href="teacherinfoTable.jsp" > 
						<div class="card text-white bg-info card-box">
							<div class="card-header">See Teacher Information </div>
							<div class="card-body">
								<h5 class="card-title text-white"></h5>
								<p class="card-text">this is needed because of if there is wrong data entery about teacher is inserted in the data base it should be modified and deleted.</p>
							</div>
						</div>
                                              </a>
					</div>
					<div class="col-md-4 col-sm-12 mb-30">
                                           <a href="<%= request.getContextPath() %>/CourseSchedule" > 
						<div class="card text-white bg-dark card-box">
							<div class="card-header">generate schedule</div>
							<div class="card-body">
								<h5 class="card-title text-white"></h5>
								<p class="card-text">After all this processes are done the schedule should generated by system algorithm.</p>
							</div>
						</div>
                                           </a> 
					</div>
				</div>
				
				
			</div>
			<div class="footer-wrap pd-20 mb-20 card-box">
				DeskApp - Bootstrap 4 Admin Template By <a href="https://github.com/dropways" target="_blank">Ankit Hingarajiya</a>
			</div>
		</div>
</body>
<script src="vendors/scripts/core.js"></script>
	<script src="vendors/scripts/script.min.js"></script>
	<script src="vendors/scripts/process.js"></script>
	<script src="vendors/scripts/layout-settings.js"></script>
	<script src="src/plugins/datatables/js/jquery.dataTables.min.js"></script>
	<script src="src/plugins/datatables/js/dataTables.bootstrap4.min.js"></script>
	<script src="src/plugins/datatables/js/dataTables.responsive.min.js"></script>
	<script src="src/plugins/datatables/js/responsive.bootstrap4.min.js"></script>
	<!-- buttons for Export datatable -->
	<script src="src/plugins/datatables/js/dataTables.buttons.min.js"></script>
	<script src="src/plugins/datatables/js/buttons.bootstrap4.min.js"></script>
	<script src="src/plugins/datatables/js/buttons.print.min.js"></script>
	<script src="src/plugins/datatables/js/buttons.html5.min.js"></script>
	<script src="src/plugins/datatables/js/buttons.flash.min.js"></script>
	<script src="src/plugins/datatables/js/pdfmake.min.js"></script>
	<script src="src/plugins/datatables/js/vfs_fonts.js"></script>
	<!-- Datatable Setting js -->
	<script src="vendors/scripts/datatable-setting.js"></script></body>
</html>
